### ISSUE TITLE
List of improvements on the nested field post v0.27.0 RC0

### ISSUE THREAD

**Issue by irevoire** [meilisearch/milli#488]
- [ ] Remove a now useless callback in the transform:
    _Originally posted by @Kerollmops in https://github.com/meilisearch/milli/pull/458#discussion_r845274181_
- [x] Use the [`smartstring`](https://docs.rs/smartstring/latest/smartstring/) crate to store the primary key in the transform. => It should improve the performance but more importantly: it'll reduce memory consumption. #493
- [x] See if we can improve the error message for the indexing of geopoints => we were able to show the complete object before. Now that's impossible but we could specify what we didn't find (latitude or longitude) => #523
- [x] Skip all the flattening if the object do not need it => rewrite a specialized version of [`oxidized-json-checker`](https://docs.rs/oxidized-json-checker/0.3.2/oxidized_json_checker/index.html) that measure the « depth » in the value (actually it's not the depth because we can have 0 object and 1 array). Maybe we could even create something even easier and faster. #494
- [x] Flatten by fields instead of by document => https://github.com/meilisearch/milli/pull/514
- [ ] Maybe we could flatten (and thus index) only the fields that are actually in use (ie in any settings)
- [ ] Maybe we could fasten the search by creating a « true » db for the attribute to [ retrieve / highlight / crop ] with all the flattened field in it at the indexing time. Not sure about this one.
- [ ] Try to make the `flatten-serde-json` crate works with obkv directly
- [x] See if there is something to do with [`bumpalo`](https://docs.rs/bumpalo/latest/bumpalo/) to make all the small allocations a lot faster when we flatten document and reuse the same buffer between each loops (basically what we're doing with the obkv currently)

**Comment by curquiza** [comment]
Also, we could add some benchmarks to bench a dataset with nested fields 😇

**Comment by Kerollmops** [comment]
I was trying to take this small one _Remove a now useless callback in the transform_, but [it looks like you use it now](https://github.com/meilisearch/milli/blob/6b0737384bbff9f0e762f34f7e9976ffd5cd944d/milli/src/update/index_documents/transform.rs#L416), am I right?

**Comment by irevoire** [comment]
Yes but now it doesn't really represent what it was :grimacing: 
https://github.com/meilisearch/milli/pull/458#discussion_r845274181

**Comment by irevoire** [comment]
Everything has been tested
