### ISSUE TITLE
Store detected Language per document during indexing

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/milli#646]
> ⚠️: This issue is not an easy one, it requires some knowledge in Rust and more work than the other issues. 
I highly encourage beginners to take another issue.

## Summary

Meilisearch automatically detects the Script and the Language during indexing and search.
Because the searches only contain small texts, it is almost impossible to efficiently detect the used Language.
However, during indexing, Meilisearch receives complete documents on which it is easier to detect the Language, And so, instead of knowing the Language used in the search query, we could know the Language used in the data where we search in.

related to: https://github.com/meilisearch/product/discussions/532#discussioncomment-3709627

### Create a new database
The first step is to create a new database [in the index](https://github.com/meilisearch/milli/blob/main/milli/src/index.rs) named `script_language_docids` in the Index that stores as the key: the `Script` concatenated to the `Language` and as the value: a `RoaringBitmap` containing all the concerned docids, be aware that the key needs a [specialized codec](https://github.com/meilisearch/milli/tree/main/milli/src/heed_codec).

**related files:**
- [index.rs](https://github.com/meilisearch/milli/blob/main/milli/src/index.rs)
- [heed_codec/](https://github.com/meilisearch/milli/tree/main/milli/src/heed_codec)

### Extract and index data
During [word position extraction](https://github.com/meilisearch/milli/blob/main/milli/src/update/index_documents/extract/extract_docid_word_positions.rs) we should store the detected languages in a hashmap linked with the docids in order to [send the hashmap](https://github.com/meilisearch/milli/blob/main/milli/src/update/index_documents/extract/mod.rs) to the main thread at the end of the extraction task.
Then the main thread will have to [store these data](https://github.com/meilisearch/milli/blob/main/milli/src/update/index_documents/typed_chunk.rs) in the `script_language_docids` database.
Be aware that the same document can contain several Languages, and so, should be indexed as the value of several Script/Language pairs.

**related files:**
- [extract_docid_word_positions.rs](https://github.com/meilisearch/milli/blob/main/milli/src/update/index_documents/extract/extract_docid_word_positions.rs)
- [(extract/)mod.rs](https://github.com/meilisearch/milli/blob/main/milli/src/update/index_documents/extract/mod.rs)
- [typed_chunk.rs](https://github.com/meilisearch/milli/blob/main/milli/src/update/index_documents/typed_chunk.rs)

### Delete data
When [removing documents](https://github.com/meilisearch/milli/blob/main/milli/src/update/delete_documents.rs), we should take care of removing the corresponding docids from the `script_language_docids` database.
Then, [when the database is cleared](https://github.com/meilisearch/milli/blob/main/milli/src/update/clear_documents.rs), the `script_language_docids` database should be cleared too.

**related files:**
- [delete_documents.rs](https://github.com/meilisearch/milli/blob/main/milli/src/update/delete_documents.rs)
- [clear_documents.rs](https://github.com/meilisearch/milli/blob/main/milli/src/update/clear_documents.rs)

## Todo
- [x] create a new database
  - [x] implementation
- [x] update this database during indexing
  - [x] implementation
  - [x] tests
- [x] update this database during deletion
  - [x] implementation
  - [x] tests

**Comment by f3r10** [comment]
Hi, I would like to give it a try. I am not a rust beginner (intermediate), but I also have never contributed to an open-source project 😅.

- I have created the new database on `index.rs`.

- I have created the HashMap on `extract_docid_word_positions.rs`  like so `<Script, RoaringBitmapCodec>` and getting Script and Language provided by Token.
   - In this part, the key should be Script +  Language creating a specialized codec 
   
- And I also have added the new variant on `typed_chunk.rs` and trying to iterate over the HashMap for adding (merging too in case of existing values? ) the pair to the new database.
 
-  I am struggling with how to serialize the struct enum `Script` from `charabia`. This is related to creating a specialized codec. 
  - Would it be necessary to use serde and bincode on charabia for deriving the serialization on `Script` and `Language`? 
  - or is another way?

**Comment by ManyTheFish** [comment]
hello @f3r10,

First, could you open a draft PR on this repo?
This way I can directly make suggestions on your code in order to help you.

> I am struggling with how to serialize the struct enum Script from charabia. This is related to creating a specialized codec.

Indeed, it is an issue, I've created a branch on Charabia [`impl-serde-on-enums`](https://github.com/meilisearch/charabia/tree/impl-serde-on-enums) where `Script` and `Language` have both a `from_name` and `name` that allows you to do create your CODEC.
if you don't know how to use my branch replace the [charabia dependency in the cargo.toml](https://github.com/meilisearch/milli/blob/55d889522b8b5b6e3dc6d5cf8d14a4f7f62c956b/milli/Cargo.toml#L12) by:
```
charabia = { git = "https://github.com/meilisearch/charabia.git", branch = "impl-serde-on-enums", default-features = false }
```

**Comment by f3r10** [comment]
awesome!! thanks, @ManyTheFish for the feedback. I am going to try to implement the specialized coded.

**Comment by f3r10** [comment]
Hi @ManyTheFish, I think I got it. I have just added the corresponding tests. 
What would be the next steps?

**Comment by curquiza** [comment]
Discussed this many, job was starting with #660 but has been merged into a temporary branch `[meilisearch:enhance-language-detection](https://github.com/meilisearch/milli/tree/enhance-language-detection)`

**Comment by ManyTheFish** [comment]
hey @curquiza, I link below the issue related to the work made here:
https://github.com/meilisearch/milli/issues/682

**Comment by curquiza** [comment]
Closed in favor of https://github.com/meilisearch/milli/issues/682 that we will moved into meilisearch soon 💪
